<?php
/**
 * ChatwootSyncStatusResponseResults
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`.
 *
 * The version of the OpenAPI document: 8.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SdkWhatsappWebMultiDevice\Model;

use \ArrayAccess;
use \SdkWhatsappWebMultiDevice\ObjectSerializer;

/**
 * ChatwootSyncStatusResponseResults Class Doc Comment
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ChatwootSyncStatusResponseResults implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ChatwootSyncStatusResponse_results';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'device_id' => 'string',
        'status' => 'string',
        'total_chats' => 'int',
        'synced_chats' => 'int',
        'total_messages' => 'int',
        'synced_messages' => 'int',
        'failed_messages' => 'int',
        'current_chat' => 'string',
        'started_at' => '\DateTime',
        'completed_at' => '\DateTime',
        'error' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'device_id' => null,
        'status' => null,
        'total_chats' => null,
        'synced_chats' => null,
        'total_messages' => null,
        'synced_messages' => null,
        'failed_messages' => null,
        'current_chat' => null,
        'started_at' => 'date-time',
        'completed_at' => 'date-time',
        'error' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'device_id' => false,
        'status' => false,
        'total_chats' => false,
        'synced_chats' => false,
        'total_messages' => false,
        'synced_messages' => false,
        'failed_messages' => false,
        'current_chat' => false,
        'started_at' => false,
        'completed_at' => false,
        'error' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'device_id' => 'device_id',
        'status' => 'status',
        'total_chats' => 'total_chats',
        'synced_chats' => 'synced_chats',
        'total_messages' => 'total_messages',
        'synced_messages' => 'synced_messages',
        'failed_messages' => 'failed_messages',
        'current_chat' => 'current_chat',
        'started_at' => 'started_at',
        'completed_at' => 'completed_at',
        'error' => 'error'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'device_id' => 'setDeviceId',
        'status' => 'setStatus',
        'total_chats' => 'setTotalChats',
        'synced_chats' => 'setSyncedChats',
        'total_messages' => 'setTotalMessages',
        'synced_messages' => 'setSyncedMessages',
        'failed_messages' => 'setFailedMessages',
        'current_chat' => 'setCurrentChat',
        'started_at' => 'setStartedAt',
        'completed_at' => 'setCompletedAt',
        'error' => 'setError'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'device_id' => 'getDeviceId',
        'status' => 'getStatus',
        'total_chats' => 'getTotalChats',
        'synced_chats' => 'getSyncedChats',
        'total_messages' => 'getTotalMessages',
        'synced_messages' => 'getSyncedMessages',
        'failed_messages' => 'getFailedMessages',
        'current_chat' => 'getCurrentChat',
        'started_at' => 'getStartedAt',
        'completed_at' => 'getCompletedAt',
        'error' => 'getError'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_IDLE = 'idle';
    public const STATUS_RUNNING = 'running';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_IDLE,
            self::STATUS_RUNNING,
            self::STATUS_COMPLETED,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('device_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('total_chats', $data ?? [], null);
        $this->setIfExists('synced_chats', $data ?? [], null);
        $this->setIfExists('total_messages', $data ?? [], null);
        $this->setIfExists('synced_messages', $data ?? [], null);
        $this->setIfExists('failed_messages', $data ?? [], null);
        $this->setIfExists('current_chat', $data ?? [], null);
        $this->setIfExists('started_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets device_id
     *
     * @return string|null
     */
    public function getDeviceId()
    {
        return $this->container['device_id'];
    }

    /**
     * Sets device_id
     *
     * @param string|null $device_id device_id
     *
     * @return self
     */
    public function setDeviceId($device_id)
    {
        if (is_null($device_id)) {
            throw new \InvalidArgumentException('non-nullable device_id cannot be null');
        }
        $this->container['device_id'] = $device_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets total_chats
     *
     * @return int|null
     */
    public function getTotalChats()
    {
        return $this->container['total_chats'];
    }

    /**
     * Sets total_chats
     *
     * @param int|null $total_chats total_chats
     *
     * @return self
     */
    public function setTotalChats($total_chats)
    {
        if (is_null($total_chats)) {
            throw new \InvalidArgumentException('non-nullable total_chats cannot be null');
        }
        $this->container['total_chats'] = $total_chats;

        return $this;
    }

    /**
     * Gets synced_chats
     *
     * @return int|null
     */
    public function getSyncedChats()
    {
        return $this->container['synced_chats'];
    }

    /**
     * Sets synced_chats
     *
     * @param int|null $synced_chats synced_chats
     *
     * @return self
     */
    public function setSyncedChats($synced_chats)
    {
        if (is_null($synced_chats)) {
            throw new \InvalidArgumentException('non-nullable synced_chats cannot be null');
        }
        $this->container['synced_chats'] = $synced_chats;

        return $this;
    }

    /**
     * Gets total_messages
     *
     * @return int|null
     */
    public function getTotalMessages()
    {
        return $this->container['total_messages'];
    }

    /**
     * Sets total_messages
     *
     * @param int|null $total_messages total_messages
     *
     * @return self
     */
    public function setTotalMessages($total_messages)
    {
        if (is_null($total_messages)) {
            throw new \InvalidArgumentException('non-nullable total_messages cannot be null');
        }
        $this->container['total_messages'] = $total_messages;

        return $this;
    }

    /**
     * Gets synced_messages
     *
     * @return int|null
     */
    public function getSyncedMessages()
    {
        return $this->container['synced_messages'];
    }

    /**
     * Sets synced_messages
     *
     * @param int|null $synced_messages synced_messages
     *
     * @return self
     */
    public function setSyncedMessages($synced_messages)
    {
        if (is_null($synced_messages)) {
            throw new \InvalidArgumentException('non-nullable synced_messages cannot be null');
        }
        $this->container['synced_messages'] = $synced_messages;

        return $this;
    }

    /**
     * Gets failed_messages
     *
     * @return int|null
     */
    public function getFailedMessages()
    {
        return $this->container['failed_messages'];
    }

    /**
     * Sets failed_messages
     *
     * @param int|null $failed_messages failed_messages
     *
     * @return self
     */
    public function setFailedMessages($failed_messages)
    {
        if (is_null($failed_messages)) {
            throw new \InvalidArgumentException('non-nullable failed_messages cannot be null');
        }
        $this->container['failed_messages'] = $failed_messages;

        return $this;
    }

    /**
     * Gets current_chat
     *
     * @return string|null
     */
    public function getCurrentChat()
    {
        return $this->container['current_chat'];
    }

    /**
     * Sets current_chat
     *
     * @param string|null $current_chat current_chat
     *
     * @return self
     */
    public function setCurrentChat($current_chat)
    {
        if (is_null($current_chat)) {
            throw new \InvalidArgumentException('non-nullable current_chat cannot be null');
        }
        $this->container['current_chat'] = $current_chat;

        return $this;
    }

    /**
     * Gets started_at
     *
     * @return \DateTime|null
     */
    public function getStartedAt()
    {
        return $this->container['started_at'];
    }

    /**
     * Sets started_at
     *
     * @param \DateTime|null $started_at started_at
     *
     * @return self
     */
    public function setStartedAt($started_at)
    {
        if (is_null($started_at)) {
            throw new \InvalidArgumentException('non-nullable started_at cannot be null');
        }
        $this->container['started_at'] = $started_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return \DateTime|null
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param \DateTime|null $completed_at completed_at
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            throw new \InvalidArgumentException('non-nullable completed_at cannot be null');
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $this->container['error'] = $error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


