<?php
/**
 * SetGroupTopicRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 6.11.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SdkWhatsappWebMultiDevice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SetGroupTopicRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SetGroupTopicRequest
 * @package     SdkWhatsappWebMultiDevice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SetGroupTopicRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SetGroupTopicRequest"
     */
    public function testSetGroupTopicRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "topic"
     */
    public function testPropertyTopic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
