<?php
/**
 * UserInfoResponseResultsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 4.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SdkWhatsappWebMultiDevice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserInfoResponseResultsTest Class Doc Comment
 *
 * @category    Class
 * @description UserInfoResponseResults
 * @package     SdkWhatsappWebMultiDevice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserInfoResponseResultsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserInfoResponseResults"
     */
    public function testUserInfoResponseResults()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verified_name"
     */
    public function testPropertyVerifiedName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "picture_id"
     */
    public function testPropertyPictureId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "devices"
     */
    public function testPropertyDevices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
