<?php
/**
 * DeviceApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`.
 *
 * The version of the OpenAPI document: 8.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SdkWhatsappWebMultiDevice\Test\Api;

use \SdkWhatsappWebMultiDevice\Configuration;
use \SdkWhatsappWebMultiDevice\ApiException;
use \SdkWhatsappWebMultiDevice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeviceApiTest Class Doc Comment
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeviceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDevice
     *
     * Add a new device.
     *
     */
    public function testAddDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDevice
     *
     * Get device info.
     *
     */
    public function testGetDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeviceStatus
     *
     * Get device connection status.
     *
     */
    public function testGetDeviceStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDevices
     *
     * List all devices.
     *
     */
    public function testListDevices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for loginDevice
     *
     * Login device with QR code.
     *
     */
    public function testLoginDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for loginDeviceWithCode
     *
     * Login device with pairing code.
     *
     */
    public function testLoginDeviceWithCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for logoutDevice
     *
     * Logout device.
     *
     */
    public function testLogoutDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reconnectDevice
     *
     * Reconnect device.
     *
     */
    public function testReconnectDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeDevice
     *
     * Remove a device.
     *
     */
    public function testRemoveDevice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
