<?php
/**
 * GroupApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 6.12.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SdkWhatsappWebMultiDevice\Test\Api;

use \SdkWhatsappWebMultiDevice\Configuration;
use \SdkWhatsappWebMultiDevice\ApiException;
use \SdkWhatsappWebMultiDevice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addParticipantToGroup
     *
     * Adding more participants to group.
     *
     */
    public function testAddParticipantToGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for approveGroupParticipantRequest
     *
     * Approve participant request to join group.
     *
     */
    public function testApproveGroupParticipantRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createGroup
     *
     * Create group and add participant.
     *
     */
    public function testCreateGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for demoteParticipantToMember
     *
     * Demote participants to member.
     *
     */
    public function testDemoteParticipantToMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportGroupParticipants
     *
     * Export group participants as CSV.
     *
     */
    public function testExportGroupParticipants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGroupInfoFromLink
     *
     * Get group information from invitation link.
     *
     */
    public function testGetGroupInfoFromLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGroupParticipantRequests
     *
     * Get list of participant requests to join group.
     *
     */
    public function testGetGroupParticipantRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGroupParticipants
     *
     * Get list of participants in a group.
     *
     */
    public function testGetGroupParticipants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupInfo
     *
     * Group Info.
     *
     */
    public function testGroupInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupInviteLink
     *
     * Group Invite Link.
     *
     */
    public function testGroupInviteLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for joinGroupWithLink
     *
     * Join group with link.
     *
     */
    public function testJoinGroupWithLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for leaveGroup
     *
     * Leave group.
     *
     */
    public function testLeaveGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for promoteParticipantToAdmin
     *
     * Promote participants to admin.
     *
     */
    public function testPromoteParticipantToAdmin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rejectGroupParticipantRequest
     *
     * Reject participant request to join group.
     *
     */
    public function testRejectGroupParticipantRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeParticipantFromGroup
     *
     * Remove participants from group.
     *
     */
    public function testRemoveParticipantFromGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGroupAnnounce
     *
     * Set group announce mode.
     *
     */
    public function testSetGroupAnnounce()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGroupLocked
     *
     * Set group locked status.
     *
     */
    public function testSetGroupLocked()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGroupName
     *
     * Set group name.
     *
     */
    public function testSetGroupName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGroupPhoto
     *
     * Set group photo.
     *
     */
    public function testSetGroupPhoto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGroupTopic
     *
     * Set group topic.
     *
     */
    public function testSetGroupTopic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
