<?php
/**
 * SendApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsApp API MultiDevice
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 4.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SdkWhatsappWebMultiDevice\Test\Api;

use \SdkWhatsappWebMultiDevice\Configuration;
use \SdkWhatsappWebMultiDevice\ApiException;
use \SdkWhatsappWebMultiDevice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SendApiTest Class Doc Comment
 *
 * @category Class
 * @package  SdkWhatsappWebMultiDevice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SendApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sendAudio
     *
     * Send Audio.
     *
     */
    public function testSendAudio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendContact
     *
     * Send Contact.
     *
     */
    public function testSendContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendFile
     *
     * Send File.
     *
     */
    public function testSendFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendImage
     *
     * Send Image.
     *
     */
    public function testSendImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendLink
     *
     * Send Link.
     *
     */
    public function testSendLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendLocation
     *
     * Send Location.
     *
     */
    public function testSendLocation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendMessage
     *
     * Send Message.
     *
     */
    public function testSendMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendPoll
     *
     * Send Poll / Vote.
     *
     */
    public function testSendPoll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendVideo
     *
     * Send Video.
     *
     */
    public function testSendVideo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
